name: Testnetify mainnet state

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * 1' # At 05:00 (UTC) on Monday, weekly

jobs:
  testnetify:
    runs-on: self-hosted
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install dependencies
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: lz4 pv wget jq
    - name: set environment
      uses: HatsuneMiku3939/direnv-action@v1
    - name: get current upgrade name
      run: |
        name=$(git describe --tags $(git rev-list --tags --max-count=1))
        archive=$(make lz4)
        echo "LZ4_ARTIFACT=${archive}" >> $GITHUB_ENV
        echo "RELEASE_TAG=${name}" >> $GITHUB_ENV
    - name: Run script
      run: make run
    - uses: ncipollo/release-action@v1
      if: ${{ !env.ACT }}
      with:
        artifacts: ${{ env.LZ4_ARTIFACT }}
        allowUpdates: true
        replacesArtifacts: true
        tag: ${{ env.RELEASE_TAG }}
