name: Run

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * 1' # At 05:00 (UTC) on Monday, weekly

jobs:
  run-script:
    runs-on: self-hosted

    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: set environment
      uses: HatsuneMiku3939/direnv-action@v1
    - name: get current upgrade name
      run: |
        name=$(git describe --tags $(git rev-list --tags --max-count=1))
        echo "RELEASE_TAG=${name}" >> $GITHUB_ENV
    - name: Run script
      run: make run
    - uses: ncipollo/release-action@v1
      with:
        artifacts: genesis.json.tar.lz4
        allowUpdates: true
        replacesArtifacts: true
        tag: ${{ env.RELEASE_TAG }}
